[project]
name = "simli-ai"
version = "2.0.2"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }

dependencies = [
    "aiortc",
    "websockets",
    "httpx",
    "numpy",
    "av>=13",
]

[project.optional-dependencies]
local = [
    "opencv-python",
    "pyaudio",
]
daily = [
    "daily-python>=0.13.0",
]
livekit = [
    "livekit-api>=0.8.0",
    "livekit>=0.18.1",
]

[tool.uv]
dev-dependencies = [
    "python-dotenv",
    "ruff",
    "ty>=0.0.17",
    "uv",
]

[project.urls]
"Homepage" = "https://github.com/simliai/simli-client-py"
"Bug Reports" = "https://github.com/simliai/simli-client-py/issues"
"Source" = "https://github.com/simliai/simli-client-py"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint.isort]
combine-as-imports = true
